all:
  hosts:
    # k8s cluster
    centos-8-01:
    centos-8-02:
    centos-8-03:
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-inventory
  # https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-aliases
  vars:
    ansible_user: vagrant
    ansible_connection: ssh
    # https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html#using-python-3-on-the-managed-machines-with-commands-and-playbooks
    #ansible_python_interpreter: /usr/bin/python
  children:
    kube-master:
      hosts:
        centos-8-01:
    etcd:
      hosts:
        centos-8-01:
        centos-8-02:
        centos-8-03:
    kube-node:
      hosts:
        # node 1
        centos-8-02:
        # node 2
        centos-8-03:
    calico-rr:
      hosts:

    k8s-cluster:
        kube-master:
        kube-node:
        calico-rr:
