apiVersion: v1
kind: Service
metadata:
  name: redis
  # These are used by selectors to link k8s objects.
  labels:
    name: redis-service
    app: docker-voting-app-demo
spec:
  ports:
      # Listening port
    - port: 6379
      # Forwarding port
      targetPort: 6379
  # Link the Service to Pods
  selector:
    name: redis-pod
    app: docker-voting-app-demo
