apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  # These are used by selectors to link k8s objects.
  labels:
    name: worker-app-pod
    app: docker-voting-app-demo
spec:
  containers:
    - name: worker-app
    # https://hub.docker.com/r/dockersamples/examplevotingapp_worker
      image: dockersamples/examplevotingapp_worker
